# Generated by Django 3.1.3 on 2021-03-28 14:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcador',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
    ]
