# Generated by Django 3.1.3 on 2021-04-17 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcador', '0002_auto_20210328_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marcador',
            options={'ordering': ('nome',)},
        ),
    ]
