# Generated by Django 3.1.3 on 2021-02-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_link_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link_media',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
