# Generated by Django 3.1.3 on 2021-02-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210228_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_foto',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
