# Generated by Django 3.1.3 on 2021-02-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_link_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link_foto',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/%Y/%m/%d'),
        ),
    ]
