# Generated by Django 3.1.3 on 2021-02-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_venda',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
