# Generated by Django 3.1.3 on 2021-02-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_link_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link_venda',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
