# Generated by Django 3.1.3 on 2021-03-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcador', '0001_initial'),
        ('products', '0007_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Marcador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcador.marcador')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
