# Generated by Django 3.1.3 on 2021-03-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcador', '0001_initial'),
        ('products', '0009_auto_20210328_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_marcador',
            name='marcador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_marcadors', to='marcador.marcador'),
        ),
    ]
