# Generated by Django 3.1.3 on 2021-04-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210328_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'imagem', 'verbose_name_plural': 'imagens'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterModelOptions(
            name='product_marcador',
            options={'verbose_name': 'produtos por marcador'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-created',), 'verbose_name': 'promoção', 'verbose_name_plural': 'promoções'},
        ),
        migrations.AlterModelOptions(
            name='sale_product',
            options={'verbose_name': 'produtos por promoção'},
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='nota',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('unlikes', models.IntegerField(default=0)),
                ('data_criado', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
