# Generated by Django 3.1.3 on 2021-04-17 13:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210417_1024'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comentario',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='post',
            new_name='product',
        ),
    ]
