# Generated by Django 3.1.3 on 2021-05-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210417_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ('-data_criado',)},
        ),
        migrations.AlterModelManagers(
            name='comentario',
            managers=[
            ],
        ),
    ]
